name: "monstercat-dl"
title: "Download Monstercat songs from your Terminal app!"
description: >-
  monstercat-dl is a PHP command line tool that allows you to download Monstercat songs from your Terminal app without any Gold account.
  You don't even need to be logged in.
baseurl: "/monstercat-dl"

current_version: "v1.0"
tool_version: "v1.0.1"

params:
  current_version: "1.0.1"
  docs_version: "1.0"
  repo: "https://github.com/d9beuD/monstercat-dl"
  url: "https://d9beuD.github.io"

  download:
    source: "https://github.com/d9beuD/monstercat-dl/archive/v1.0.1.zip"
    phar: "https://github.com/d9beuD/monstercat-dl/releases/download/v1.0.1/monstercat-dl.phar"

# Build settings
markdown: kramdown

collections:
  docs:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "Download Monstercat songs from your Terminal app!"
