# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: monstercat-dl
title: Download Monstercat songs from your Terminal app!
description: >- # this means to ignore newlines until "baseurl:"
  monstercat-dl is a PHP command line tool that allows you to download Monstercat songs from your Terminal app without any Gold account.
  You don't event need to be logged in.
baseurl: "/monstercat-dl" # the subpath of your site, e.g. /blog
url: "https://d9beuD.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "https://github.com/d9beuD/monstercat-dl"

# Build settings
markdown: kramdown

collections:
  docs:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
